### ISSUE TITLE
Lazy loading of large search result sets for Politician search

### ISSUE THREAD

**Issue by hhubik** [vis/poltrack#20]
Follow instructions in the [App Demo](https://github.com/vis/poltrack/wiki/Development-Status).  The full result set for search in `Step 3` 
can be be quite large.  The back-end will return the results in small batches (pages). Perhaps 5 or 10 at a time. 

There needs to be a way for the user to get the next page of results by clicking a "Load More Results" button placed at the bottom of the most recent search result batch.

- [x] Design complete
- [x] Implementation complete

**Comment by hhubik** [comment]
@teraSurfer please let me know if you are still planning on doing this.

**Comment by teraSurfer** [comment]
@hhubik yes I am. I sent a couple of emails with a few questions.

**Comment by hhubik** [comment]
@teraSurfer   I am sorry if I missed any messages.  I don't recall seeing anything from since about May 18.  If you sent any messages after that date, please re-send them or post them as comments here. Thanks!

**Comment by teraSurfer** [comment]
@hhubik  I've sent the email again. Please let me know what you think about it.

**Comment by hhubik** [comment]
Excerpt from my email message on this topic in response to email from @teraSurfer from May 22:

I would prefer a solution that would allow us to display more than one search result item at a time. The infinite scrolling approach would be fine with me.

Not sure if it is important for the UI implementation, but the search results will be coming from Azure Search in response to one or more search queries. [Here](https://docs.microsoft.com/en-us/azure/search/search-pagination-page-layout) is a write-up on how Azure search supports paging.  The final search API will look pretty closely match that.

**Comment by teraSurfer** [comment]
@hhubik I'll go through the Azure search docs and will let you know my thoughts soon.

**Comment by hhubik** [comment]
Hi @teraSurfer I am having some doubts about the infinite scrolling.  Could we just load the first ten search results and have a "Load More" button at the bottom that would load ten more when clicked by the user?  Something like this?

![image](https://user-images.githubusercontent.com/14813201/60386612-42868f80-9a65-11e9-9db8-c5a9e8a77ef4.png)

**Comment by teraSurfer** [comment]
Yes I can do that.

**Comment by teraSurfer** [comment]
@hhubik I went through the azure docs the end points seem similar to what I have worked with before so having $top, $skip and $count should be enough to implement the above format.

**Comment by hhubik** [comment]
@teraSurfer Perfect. Thanks!

**Comment by teraSurfer** [comment]
@hhubik I'll be working on this issue today. Will give an update on my progress soon. As far as the pagination is concerned, How do I query it from front-end?

**Comment by hhubik** [comment]
@teraSurfer 

Please sync your fork with the project master branch using the instructions [here](https://github.com/vis/poltrack/blob/master/CONTRIBUTING.md).  Last night we updated the project to the latest version of Angular.  

Regarding the query, I will get back to you shortly.

**Comment by hhubik** [comment]
Hi Achalaesh,

A small change.  Please start with the “Select Politician” query (as opposed the “By Action Keyword” query.  The paging will be the same for both.

Here is the query info.  I am sending it via email rather than adding it to the issue on Github as the message includes API keys.

This should allow you to start working on the actor/politician search.

On line 57 of report-card.service, replace `http://localhost:7071/api/ActorSearch?q=${searchString}`
with

https://poltrack-test.search.windows.net/indexes/actors/docs/?api-version=2019-05-06&api-key=7D0C4347B4C5296A1D309E3AC07E0686&$count=true&$orderby=isCurrentOfficeHolder%20desc&search=smith

This is an Azure Search endpoint.  You should be able to modify the query as you need to support the paging per the document I had mentioned earlier.  Let’s just start with displaying 6 search results at a time.  The above query returns 20 search results.

The data returned by Azure Search uses different property names than the app currently expects (was receiving from the poltrack test server).
I am working on fixing it, but I don’t want to hold you up.  So if you want to go ahead and use the Azure search query right away, you would need to modify the toActorSearchResultItems method report-card service to correctly convert the Azure search results to the ActorSearchResult object  used by the app.

Here is the mapping between the properties of the ActorSearchResult object (which is just a wrapper for the Actor object) and the properties returned by the Azure Search query:

export interface Actor {                                                                 Azure Search Json Property
  /** calculated from personId and officeId */
  id: string;
  personId: string;                                                                             personId
  officeId: string;                                                                               officeHeldId
  title: string;                                                                                       title_en_US
  description: string;                                                                        description_en_US
  termStarted: Date;                                                                        startDT
  termEnded: Date;                                                                          endDT
}

Here is an example of the Azure Search Data:

{
    "@odata.context": "https://poltrack-test.search.windows.net/indexes('actors')/$metadata#docs(*)",
    "@odata.count": 7,
    "value": [
        {
            "@search.score": 2.0382688,
            "officeHeldId": "vdb-1991",
            "personId": "vdb-1639",
           "status": [
                "approved"
            ],
            "statusLastChangedDT": "2019-06-21T04:00:00Z",
            "title_en_US": "Kennedy, John N",
            "description_en_US": "Senator, Louisiana",
            "startDT": "2017-01-03T05:00:00Z",
            "endDT": null,
            "tags": [],
            "isCurrentOfficeHolder": true
        },

If you have any questions, please let know.

I need to step out, but will be back at my computer in about 3 hours.

Thanks,

Hubert

**Comment by teraSurfer** [comment]
@hhubik Im facing a cors error. For now, I'll use a proxy to hit the poltrack-test-search url but we may need a solution in place for future.

**Comment by hhubik** [comment]
Hi Achalaesh,

Sorry! I tested the query from a browser and forgot about the CORS issue.  I will look into the real fix.

What proxy do you use as a workaround?  I have found
https://corsproxy.github.io/
Is there something better/different?

Hubert

________________________________

**Comment by teraSurfer** [comment]
I generally prefer cors-anywhere it is more reliable. [https://cors-anywhere.herokuapp.com](https://cors-anywhere.herokuapp.com)

**Comment by teraSurfer** [comment]
Hey @hhubik, Happy 4th! This is taking me a little longer than I expected but I should be able to complete it by monday.

**Comment by hhubik** [comment]
Hi @teraSurfer No problem.  Take your time.  Thanks for the update. Happy 4th to you too!

**Comment by hhubik** [comment]
Hi @teraSurfer , I have the test cloud back end working that returns realistic data for the Politician (Step 1) query.  I have also just made a commit in the master branch that makes the app use the cloud for the Politician query and also includes a first pass of the Politician search result paging.  It's not pretty, but it kind of works.

One thing that is definitely missing is scrolling of the data when a new page is loaded.  Right now the main app window just grows as you load additional search result pages.  I have time and want to try to add the search result scrolling, that would be great. 

To get a multi-page result from the Politician search, search for `smith` or `congressman`.

Before you do anything, please sync your fork with the project master branch.

I will continue working on the back end for the two queries in Step 2 (`Select Info Providers`).

**Comment by teraSurfer** [comment]
Thanks for the information @hhubik, I'll sync the fork and work on it.

**Comment by hhubik** [comment]
Completed as of September 18, 2019.
