### ISSUE TITLE
UI Improvements: esthetics, usability, responsive design (compatibility with variety of devices).

### ISSUE THREAD

**Issue by hhubik** [vis/poltrack#25]
Hi @andyalam Please use this issue for the UI improvements. Thanks!

**Comment by hhubik** [comment]
Related to #19.

**Comment by hhubik** [comment]
Hi @andyalam I have just made a commit to the master branch on GitHub that makes the app use a test cloud back end for the Step 1 query (Actor/Politician search).  The commit also include a first past on the paging of the search results (also for the first query).  It's not pretty, but it kind of works.

Please sync your fork with the master branch using the instructions [here](https://github.com/vis/poltrack/blob/master/CONTRIBUTING.md).

If you still have time left, please look over the changes in commit 6cc61c04cea74744272bfb003b8ce3dc97c375a3 and let me know if there are any serious issues I should fix.

To see the paging working, query for `smith` or `congressman`.  Both of those should return many matches (though the paging limited to three pages max).

Thanks!

**Comment by andyalam** [comment]
Hi @hhubik, I'm doing some finishing touches on mobile improvements for the report card screen, I'll have them up by tomorrow.

No issues to note, looks good!

**Comment by hhubik** [comment]
@andyalam thanks!

**Comment by hhubik** [comment]
Pull request merged.
